### ISSUE TITLE
missing Utils module

### ISSUE THREAD

**Issue by mwotton** [LeifW/xmonad-utils#1]
Where's the Utils module? I get this from cabal installing:

Preprocessing executable 'hslock' for xmonad-utils-0.1.3...

src/Hslock.hsc:37:8:
    Could not find module `Utils'
    Perhaps you meant Util (from ghc-7.4.1)
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
xmonad-utils-0.1.3 failed during the building phase. The exception was:
ExitFailure 1

**Comment by LeifW** [comment]
It's in src/Utils.hs.  It's imported by Hhp.hs and Hslock.hsc.  This all works for me if I do "cabal configure; cabal build" on GHC 7.4.2. 
Is there something else I need to do to note Utils.hs in the .cabal file?  Sorry, I'm pretty new to Cabal.

**Comment by mwotton** [comment]
i can't check it on hackage because it's down, but working off "cabal unpack xmonad-utils", it doesn't show up. You might have to put it in the Other-Modules list in the cabal file for cabal sdist to put it in the tarball.

**Comment by LeifW** [comment]
Should be cabal-installable now.  Thanks for your help!

**Comment by mwotton** [comment]
no probs :)
