### ISSUE TITLE
What is override-redirect?

### ISSUE THREAD

**Issue by Tarrasch** [LeifW/xmonad-utils#8]
Can there be some more documentation about `hmanage` in the README perhaps?

**Comment by LeifW** [comment]
Good question. I've never used it.  I found this description: http://wiki.tcl.tk/9870
Also found usage discussed on http://stackoverflow.com/questions/8867715/xlib-center-window.
I could add a link to there from the README?

**Comment by LeifW** [comment]
Also, speaking of the README: hxput should go on there too. It's kind of the reverse of hxsel.

**Comment by Tarrasch** [comment]
Cool! I made a pull request! :)

**Comment by Tarrasch** [comment]
PR was merged. Thanks!
